### ISSUE TITLE
Searching for new location after first search has no action

### ISSUE THREAD

**Issue by julietshen** [shermangore/SkyVibe#9]
After an initial search for a city (ie Milan, Italy) I tried searching for Atlanta, GA. While the map autopopulates with search results, clicking it does nothing and the map is then stuck there, unable to be closed.

<img width="709" alt="screen shot 2017-06-14 at 10 40 58 pm" src="https://user-images.githubusercontent.com/8658907/27166907-a4d6f07a-5152-11e7-87a1-ec18291749e2.png">

**Comment by shermangore** [comment]
Fixed by appending new search box each time maps div is toggled to "visible".
